name: hackaton_app
description: A new Flutter application.



version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^0.1.3
  flutter_spinkit: ^4.1.2+1
  http: ^0.12.1
  google_fonts: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true
  fonts:
    - family: Haike
      fonts:
        - asset: fonts/Haike-Regular.ttf
    - family: Palm Canyon Drive
      fonts:
        - asset: fonts/PalmCanyonDrive.otf
    - family: Parker
      fonts:
        - asset: fonts/Parker.ttf
