name: hackaton_app
description: A new Flutter application.



version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_spinkit: ^4.1.2+1
  date_picker_timeline: any 
  http: ^0.12.1
  google_fonts: ^1.1.0
  animated_text_kit: ^2.2.0
  preferences: ^5.0.2
  shared_preferences: ^0.5.6
  page_transition: ^1.1.5

  flutter_launcher_icons: ^0.7.5
  get_it: ^4.0.2
  rxdart: 0.24.1
  url_launcher: ^5.4.11

flutter_icons:
  android: true
  ios: true
  image_path: "icon/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Haike
      fonts:
        - asset: fonts/Haike-Regular.ttf
    - family: Palm Canyon Drive
      fonts:
        - asset: fonts/PalmCanyonDrive.otf
    - family: Parker
      fonts:
        - asset: fonts/Parker.ttf
