name: hackaton_app
description: A new Flutter application.



version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_spinkit: ^4.1.2+1
  date_picker_timeline: any 
  http: ^0.12.1

  get_it: ^4.0.2
  rxdart: 0.24.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true

